language: python

services:
    - docker
    
before_install:
    - docker-compose up &
   
install:
    - pip install -r ./test/requirements.txt
    
before_script:
    - docker-compose run --user=root --entrypoint chown worker_test -R myuser:myuser .
    
script:
    pytest ./test
