language: python

services:
    - docker
    
before_install:
    - docker-compose up &
    - chmod +r -R /var/html
   
install:
    - pip install -r ./test/requirements.txt
    
script:
    pytest ./test
