language: python

services:
    - docker
    
before_install:
    - docker build ./ -t apachetest
    - docker run -dit -p 80:80 apachetest --name test-webserver
    
install:
    - pip install -r ./test/requirements.txt
    
script:
    pytest --rootdir=./test