version: '3'

services:
   mysql:
      restart: always 
      build: ./db
      environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_USER=testuser
         - MYSQL_PASS=password
      ports:
         - 3306:3306
#      volumes:
#         - ./dbdata:/docker-entrypoint-initdb.d
   server:
      build: ./apache
      ports:
         - 80:80
      volumes:
         - ./html:/var/www/html
