version: '3'

services:
   mysql:
      restart: always 
      build: ./db
      environment:
         MYSQL_DATABASE: 'csecfinal'
         MYSQL_ROOT_PASSWORD: 'password'
         MYSQL_USER: 'testuser'
         MYSQL_PASS: 'password'
      ports:
         - 3306:3306
#      volumes:
#         - ./dbdata:/docker-entrypoint-initdb.d
   server:
      image: php:7.3-apache
      ports:
         - 80:80
      volumes:
         - ./html:/var/www/html
